### ISSUE TITLE
TLS termination

### ISSUE THREAD

**Issue by elvyscruz** [coopernurse/maelstrom#93]
Is there a way to add TLS termination to Maelstrom to serve https? Internal containers are just HTTP but I would like to serve https for all projects that are being proxied.

**Comment by coopernurse** [comment]
Hello!  TLS is not currently supported, but it's something I'd like to add.  One option would be to integrate Matt Holt's https://github.com/caddyserver/certmagic library.

There's a separate but related issue which is to add TLS to the private maelstrom port to secure communication between nodes. For this feature I think using a self-signed cert is probably more appropriate. But we should probably make a separate issue to track that.

Let me know if you have interest in working on adding TLS. I'm working on redoing the maelstrom web site at the moment, but when I finish that perhaps I can dust off the CertMagic experiments I did a couple of years ago.

**Comment by elvyscruz** [comment]
Thanks, I'll look into certmagic. I'll close this issue as this is more like a feature request. Maelstrom is a great piece of software, I think it should be promoted on [hackernews](https://news.ycombinator.com/) to attract more developers and grow the community around it
